version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: on-failure
    container_name: lilac_backend_container
    image: lilac_backend
    env_file:
      - secrets.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: on-failure
    container_name: lilac_frontend_container
    image: lilac_frontend
