spring:
  config:
    activate:
      on-profile: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lilac_mysql?serverTimezone=Asia/Seoul
    username: ssafy
    password: ssafy

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
      open-in-view: true

  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      database: lilac_mongodb
      username: ssafy
      password: ssafy

  redis:
    lettuce:
      pool:
        max-active: 5
        max-idle: 5
        min-idle: 2
    host: localhost
    port: 6379

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

jwt:
  header: Authorization
  secret: hellothisislilacmusicsdevelopversionsecretkey
  access-token-validity-milliseconds: 1800000
  refresh-token-validity-milliseconds: 604800000

logging:
  level:
    root: info
    com.lilacmusic: debug

#cloud:
#  aws:
#    s3:
#      bucket:
#    region:
#      static: ap-northeast-2
#    stack:
#      auto: false
#    cloudfront:

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_ID}
            redirect-uri: "http://localhost:8080/api/v1/oauth2/code/kakao"
            client-authentication-method: POST
            client-secret: ${KAKAO_SECRET}
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client_name: kakao

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id